// Generated by CoffeeScript 1.12.4
(function() {
  var $, Firebase, Model, Spine, User,
    extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    hasProp = {}.hasOwnProperty;

  Spine = this.Spine || require('spine');

  $ = Spine.$;

  Firebase = (function(superClass) {
    extend(Firebase, superClass);

    function Firebase(params) {
      Firebase.__super__.constructor.apply(this, arguments);
    }

    Firebase.prototype.initFirebase = function(config) {
      var ctr;
      ctr = this;
      firebase.initializeApp(config);
      return firebase.auth().onAuthStateChanged((function(userParams) {
        if (!userParams) {
          ctr.trigger('firebaseAuthOut');
        } else {
          userParams.getToken().then(function(accessToken) {
            userParams['accessToken'] = accessToken;
            ctr.appUser = new User(userParams);
            return ctr.trigger('firebaseAuthIn');
          });
        }
        return ctr.trigger('firebaseAuthToggle');
      }), function(error) {
        return ctr.log('auth error', error);
      });
    };

    Firebase.signOut = function() {
      var ctr, jq_deferred, promise;
      if (!firebase.auth().currentUser) {
        return;
      }
      ctr = this;
      jq_deferred = $.Deferred();
      promise = deferred.promise();
      firebase.auth().signOut().then(function() {
        if (ctr.appUser) {
          delete ctr.appUser;
        }
        return jq_deffered.resolve();
      });
      return promise;
    };

    return Firebase;

  })(Spine.Controller);

  Model = {
    extended: function() {
      if (!firebase) {
        return;
      }
      if (!this.ref) {
        error('Please add variable \'ref\' to a Spine.Firebase.Model');
      }
    },
    update: function() {
      var promise, u_deferred;
      if (!this.fbref) {
        this.fbref = firebase.database().ref(this.ref);
      }
      u_deferred = $.Deferred();
      promise = u_deferred.promise();
      this.fbref.child(this.id).update(this.attributes()).done(function() {
        console.log('firebase update', this.attributes());
        return u_deferred != null ? u_deferred.resolve() : void 0;
      });
      return promise;
    },
    load: function(options) {
      var l_deferred, promise;
      if (options == null) {
        options = {};
      }
      if (!this.fbref) {
        this.fbref = firebase.database().ref(this.ref);
      }
      if (!options.hasOwnProperty('clear')) {
        options.clear = true;
      }
      l_deferred = $.Deferred();
      promise = l_deferred.promise();
      this.fbref.on('value', (function(_this) {
        return function(data) {
          _this.refresh(data.val() || [], options);
          if (l_deferred != null) {
            l_deferred.resolve(data.val());
          }
          return console.log('firebase load', data.val());
        };
      })(this));
      return promise;
    },
    loadOnce: function(options) {
      var l_deferred, promise;
      if (options == null) {
        options = {};
      }
      if (!this.fbref) {
        this.fbref = firebase.database().ref(this.ref);
      }
      if (!options.hasOwnProperty('clear')) {
        options.clear = true;
      }
      l_deferred = $.Deferred();
      promise = l_deferred.promise();
      this.fbref.once('value', (function(_this) {
        return function(data) {
          _this.refresh(data.val() || [], options);
          if (l_deferred != null) {
            l_deferred.resolve(data.val());
          }
          return console.log('firebase load', data.val());
        };
      })(this));
      return promise;
    },
    off: function() {
      var ref;
      return (ref = this.fbref) != null ? ref.off() : void 0;
    }
  };

  User = (function() {
    function User(params) {
      this.displayName = params.displayName;
      this.email = params.email;
      this.emailVerified = params.emailVerified;
      this.photoURL = params.photoURL;
      this.isAnonymous = params.isAnonymous;
      this.uid = params.uid;
      this.accessToken = params.accessToken;
    }

    return User;

  })();

  Firebase.Model = Model;

  Firebase.User = User;

  Spine.Firebase = Firebase;

  if (typeof module !== "undefined" && module !== null) {
    module.exports = Firebase;
  }

}).call(this);
